name: CI for Model Training and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Izin default sudah cukup di sini
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python and MLflow
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install mlflow

      - name: Run MLflow Project to train model
        # Perintah ini akan membaca file MLProject dan menjalankan training
        # Hasilnya akan tersimpan di folder 'mlruns'
        run: mlflow run ./MLProject

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        # Ganti 'username_anda' dengan username Docker Hub Anda
        # Perintah ini akan mengambil model terakhir dari mlruns dan membuat Docker image
        run: mlflow models build-docker --model-uri "runs:/$(ls -t mlruns/0/ | head -1)/artifacts/model" --name "hafelen09/churn-prediction-model"
