name: CI for Model Training and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.12'

      - name: Install MLflow
        run: pip install mlflow

      - name: Run MLflow Project to train model
        shell: bash -l {0}
        run: mlflow run ./MLProject

      # Langkah 1: Simpan ID dari run terbaru ke dalam variabel RUN_ID
      - name: Get latest MLflow run ID
        run: echo "RUN_ID=$(ls -t mlruns/0 | head -1)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Langkah 2: Gunakan variabel RUN_ID untuk membuat path yang benar
      - name: Build and push Docker image
        # Ganti 'username_anda' dengan username Docker Hub Anda
        run: mlflow models build-docker --model-uri "mlruns/0/${{ env.RUN_ID }}/artifacts/model" --name "hafelen09/churn-prediction-model"
