name: CI for Model Training and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.12'

      - name: Install MLflow
        run: pip install mlflow

      # Langkah 1: Jalankan MLflow dan simpan log-nya ke file
      - name: Run MLflow Project and capture output
        shell: bash -l {0}
        run: mlflow run ./MLProject 2>&1 | tee mlflow_run_output.txt

      # Langkah 2: Ekstrak Run ID dari file log
      - name: Extract Run ID from log
        id: get_run_id
        run: |
          RUN_ID=$(grep "Finished run with ID" mlflow_run_output.txt | sed 's/.*ID: //;s/ ===//')
          echo "RUN_ID=${RUN_ID}" >> $GITHUB_ENV
          echo "Extracted Run ID is: ${RUN_ID}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Langkah 3: Gunakan variabel RUN_ID yang sudah pasti benar
      - name: Build and push Docker image
        # Ganti 'username_anda' dengan username Docker Hub Anda
        run: mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "hafelen09/churn-prediction-model"
