name: Diagnostic - Hello World Test

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World! Jika Anda melihat pesan ini, workflow berhasil di-update."
